GolfScorecard.UI/Models/ErrorViewModel.cs
namespace GolfScorecard.UI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

GolfScorecard.UI/Controllers/HomeController.cs
using GolfScorecard.UI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GolfScorecard.UI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

GolfScorecard.UI/Controllers/ScorecardsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Golfscorecard.DAL.Entities;
using Golfscorecard.DAL.Interface.Implementation;
using Golfscorecard.DAL.Interface;
using GolfScorecard.BL.Interface;

namespace GolfScorecard.UI.Controllers
{
    public class ScorecardsController : Controller
    {
        private readonly IScorecardService _scorecardService;

        public ScorecardsController(IScorecardService scorecardService)
        {
            _scorecardService = scorecardService;
        }

        // GET: Scorecards
        public async Task<IActionResult> Index()
        {
            return View(_scorecardService.GetAllScorecards());
        }

        // GET: Scorecards/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _scorecardService.GetAllScorecards() == null)
            {
                return NotFound();
            }

            var scorecard = _scorecardService.GetScoreCard(id.Value);
            if (scorecard == null)
            {
                return NotFound();
            }

            return View(scorecard);
        }

        // GET: Scorecards/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Scorecards/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ScorecardId,HoleNumber,PlayerOne,PlayerTwo,PlayerThree,PlayerFour")] Scorecard scorecard)
        {
            if (ModelState.IsValid)
            {
                var validationCheck = _scorecardService.Validate(scorecard);

                if(!validationCheck.Item1)
                    throw new Exception(validationCheck.Item2);

                _scorecardService.AddScorecard(scorecard);
                
                return RedirectToAction(nameof(Index));
            }
            return View(scorecard);
        }

        // GET: Scorecards/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _scorecardService.GetAllScorecards() == null)
            {
                return NotFound();
            }

            var scorecard = _scorecardService.GetScoreCard(id.Value);
            if (scorecard == null)
            {
                return NotFound();
            }
            return View(scorecard);
        }

        // POST: Scorecards/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ScorecardId,HoleNumber,PlayerOne,PlayerTwo,PlayerThree,PlayerFour")] Scorecard scorecard)
        {
            if (id != scorecard.ScorecardId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _scorecardService.UpdateScoreCard(scorecard);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ScorecardExists(scorecard.ScorecardId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(scorecard);
        }

        // GET: Scorecards/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _scorecardService.GetAllScorecards() == null)
            {
                return NotFound();
            }

            var scorecard = _scorecardService.GetScoreCard(id.Value);
            if (scorecard == null)
            {
                return NotFound();
            }

            return View(scorecard);
        }

        // POST: Scorecards/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            _scorecardService.DeleteScorecard(id);

            return RedirectToAction(nameof(Index));
        }

        private bool ScorecardExists(int id)
        {
          return (_scorecardService.GetAllScorecards()?.Any(e => e.ScorecardId == id)).GetValueOrDefault();
        }
    }
}

GolfScorecard.UI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

GolfScorecard.UI/Views/Scorecards/Create.cshtml
@model Golfscorecard.DAL.Entities.Scorecard

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Scorecard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="HoleNumber" class="control-label"></label>
                <input asp-for="HoleNumber" class="form-control" />
                <span asp-validation-for="HoleNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerOne" class="control-label"></label>
                <input asp-for="PlayerOne" class="form-control" />
                <span asp-validation-for="PlayerOne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerTwo" class="control-label"></label>
                <input asp-for="PlayerTwo" class="form-control" />
                <span asp-validation-for="PlayerTwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerThree" class="control-label"></label>
                <input asp-for="PlayerThree" class="form-control" />
                <span asp-validation-for="PlayerThree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerFour" class="control-label"></label>
                <input asp-for="PlayerFour" class="form-control" />
                <span asp-validation-for="PlayerFour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GolfScorecard.UI/Views/Scorecards/Delete.cshtml
@model Golfscorecard.DAL.Entities.Scorecard

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Scorecard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoleNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoleNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerOne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerOne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerTwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerTwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerThree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerThree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerFour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerFour)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ScorecardId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

GolfScorecard.UI/Views/Scorecards/Details.cshtml
@model Golfscorecard.DAL.Entities.Scorecard

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Scorecard</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HoleNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HoleNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerOne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerOne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerTwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerTwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerThree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerThree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PlayerFour)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PlayerFour)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ScorecardId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

GolfScorecard.UI/Views/Scorecards/Edit.cshtml
@model Golfscorecard.DAL.Entities.Scorecard

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Scorecard</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ScorecardId" />
            <div class="form-group">
                <label asp-for="HoleNumber" class="control-label"></label>
                <input asp-for="HoleNumber" class="form-control" />
                <span asp-validation-for="HoleNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerOne" class="control-label"></label>
                <input asp-for="PlayerOne" class="form-control" />
                <span asp-validation-for="PlayerOne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerTwo" class="control-label"></label>
                <input asp-for="PlayerTwo" class="form-control" />
                <span asp-validation-for="PlayerTwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerThree" class="control-label"></label>
                <input asp-for="PlayerThree" class="form-control" />
                <span asp-validation-for="PlayerThree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PlayerFour" class="control-label"></label>
                <input asp-for="PlayerFour" class="form-control" />
                <span asp-validation-for="PlayerFour" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GolfScorecard.UI/Views/Scorecards/Index.cshtml
@model IEnumerable<Golfscorecard.DAL.Entities.Scorecard>

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.HoleNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerOne)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerTwo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerThree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PlayerFour)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.HoleNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerOne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerTwo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerThree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PlayerFour)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ScorecardId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ScorecardId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ScorecardId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

GolfScorecard.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GolfScorecard.UI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GolfScorecard.UI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Scorecards" asp-action="Index">GolfScorecard</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Scorecards" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GolfScorecard.UI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>